[package]
name = "cice-action"
version = "0.1.0"
edition = "2021"

[dependencies]
cice-core = { version = "0.1.0", path = "../cice-core" }
euclid = { version = "0.22.11", features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
