name: cice-controller

on:
  push:
    path:
      - '.github/workflows/controller.yml'
      - 'crates/cice-controllers/**'
      - 'crates/cice-core/**'
  pull_request:
    path:
      - '.github/workflows/controller.yml'
      - 'crates/cice-controllers/**'
      - 'crates/cice-core/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  controller-vnc:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nightly Rust Toolchain
        run: rustup update nightly
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build -p cice-controller-vnc --verbose
      - name: Clippy
        run: cargo clippy -p cice-controller-vnc --verbose
      - name: Run tests
        run: cargo test -p cice-controller-vnc  --verbose
