name: cice-core

on:
  push:
    path:
      - ".github/workflows/core.yml"
      - "crates/cice-core/**"
  pull_request:
    path:
      - ".github/workflows/core.yml"
      - "crates/cice-core/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nightly Rust Toolchain
        run: rustup update nightly
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build -p cice-core --verbose
      - name: Clippy
        run: cargo clippy -p cice-core --verbose
      - name: Run tests
        run: cargo test -p cice-core  --verbose
