name: cice-recognizer

on:
  push:
    path:
      - ".github/workflows/recognizer.yml"
      - "crates/cice-recognizers/**"
      - "crates/cice-core/**"
      - "Cargo.toml"
  pull_request:
    path:
      - ".github/workflows/recognizer.yml"
      - "crates/cice-recognizers/**"
      - "crates/cice-core/**"
      - "Cargo.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  recognizer-opencv:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        opencv-version:
          - 4.11.0
        include:
          - os: macos-latest
            version:
              brew: "@4"
    runs-on: ${{ matrix.os }}
    env:
      #Atlas_ROOT_DIR: /usr/include/ # for cmake to find lapacke.h
      OPENCV_VERSION: ${{ matrix.opencv-version }}
      BREW_OPENCV_VERSION: ${{ matrix.version.brew }}
      #OPENCV_LINKAGE: ${{ matrix.linkage }}
      # SCCACHE_GHA_ENABLED: "true"
      # RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v4
      - name: Install Nightly Rust Toolchain
        run: rustup update nightly
      - uses: Swatinem/rust-cache@v2
      - name: Install Opencv Dependencies
        run: script/dependency/opencv/install.sh
        shell: bash
      - name: Test
        run: script/ci/opencv/script.sh
        shell: bash
